2020/04/16 23:54:12 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:14 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:17 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:20 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:22 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:25 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:30 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:37 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:54:51 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:55:17 [emerg] 1#1: unknown directive "Django" in /etc/nginx/sites-available/my_nginx.conf:17
2020/04/16 23:55:57 [crit] 8#8: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/16 23:55:57 [crit] 8#8: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:01:05 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:01:05 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:01:41 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:01:41 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:03:05 [crit] 6#6: *9 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:03:05 [crit] 6#6: *9 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:35 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:35 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:37 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:37 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:38 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:38 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:38 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:38 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:39 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:39 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:39 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:39 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:39 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:39 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:40 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /graphql HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:40 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/graphql"
2020/04/17 00:15:41 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:42 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:15:54 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:15:54 [crit] 7#7: *2 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:22:31 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:22:31 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:22:31 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:22:33 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:22:33 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:22:33 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost"
2020/04/17 00:22:33 [crit] 6#6: *1 connect() to unix:/trackapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/trackapp/app.sock:", host: "localhost", referrer: "http://localhost/"
2020/04/17 00:25:16 [error] 7#7: *1 directory index of "/app/static/" is forbidden, client: 172.30.0.1, server: localhost, request: "GET /static/ HTTP/1.1", host: "localhost"
